/**
 * Odisha Blood Bank & Hospital Stock Dataset
 * Aligned with e-BloodBank Odisha, e-RaktKosh & Odisha State Blood Transfusion Council (OSBTC)
 */

export const ODISHA_DISTRICTS = [
  'ALL',
  'Cuttack',
  'Khurda (Bhubaneswar)',
  'Ganjam (Berhampur)',
  'Sambalpur (Burla)',
  'Balasore',
  'Mayurbhanj (Baripada)',
  'Koraput',
  'Sundargarh (Rourkela)',
  'Puri',
  'Angul',
  'Kalahandi',
  'Kendrapada',
  'Bolangir'
];

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Bombay Group (Rare)'];

export const BLOOD_COMPONENTS = [
  { id: 'WHOLE', en: 'Whole Blood', or: 'ସମ୍ପୂର୍ଣ୍ଣ ରକ୍ତ', hi: 'संपूर्ण रक्त' },
  { id: 'PRBC', en: 'Packed Red Blood Cells (PRBC)', or: 'ପ୍ୟାକ୍ଡ୍ ରେଡ୍ ବ୍ଲଡ୍ ସେଲ୍ (PRBC)', hi: 'पैक रेड ब्लड सेल्स (PRBC)' },
  { id: 'FFP', en: 'Fresh Frozen Plasma (FFP)', or: 'ଫ୍ରେସ୍ ଫ୍ରୋଜନ୍ ପ୍ଲାଜ୍ମା (FFP)', hi: 'ताजा फ्रोजन प्लाज्मा (FFP)' },
  { id: 'PLATELETS', en: 'Platelet Concentrate (RDP)', or: 'ପ୍ଲେଟଲେଟ୍ କନସେଣ୍ଟ୍ରେଟ୍ (RDP)', hi: 'प्लेटलेट सांद्रता (RDP)' },
  { id: 'SDP', en: 'Single Donor Platelets (SDP/Apheresis)', or: 'ସିଙ୍ଗଲ୍ ଡୋନର୍ ପ୍ଲେଟଲେଟ୍ (SDP)', hi: 'सिंगल डोनर प्लेटलेट्स (SDP)' }
];

export const ODISHA_BLOOD_BANKS = [
  {
    id: 'BB-CTC-001',
    name: 'Central Red Cross Blood Bank, SCB Medical College',
    nameOdia: 'ସେଣ୍ଟ୍ରାଲ୍ ରେଡ୍ କ୍ରସ୍ ରକ୍ତ ଭଣ୍ଡାର, SCB ମେଡିକାଲ୍ କଲେଜ୍',
    hospitalName: 'SCB Medical College & Hospital',
    district: 'Cuttack',
    city: 'Cuttack',
    address: 'Mangalabag, SCB Medical College Campus, Cuttack - 753007',
    category: 'Govt / Regional Transfusion Center',
    bskyCovered: true,
    helpline: '+91 671 2414080 / 104',
    nodalOfficer: 'Dr. Pankajini Mallick (Director, RBTC)',
    nodalPhone: '+91 94370 88210',
    email: 'bloodbank.scb@odisha.gov.in',
    operatingHours: '24x7 Emergency & Routine',
    lastUpdated: '2026-09-09T09:30:00.000Z',
    stock: {
      'A+': { WHOLE: 18, PRBC: 34, FFP: 42, PLATELETS: 14, SDP: 4 },
      'A-': { WHOLE: 3, PRBC: 5, FFP: 8, PLATELETS: 2, SDP: 1 },
      'B+': { WHOLE: 24, PRBC: 48, FFP: 55, PLATELETS: 20, SDP: 6 },
      'B-': { WHOLE: 4, PRBC: 6, FFP: 10, PLATELETS: 3, SDP: 1 },
      'AB+': { WHOLE: 12, PRBC: 22, FFP: 30, PLATELETS: 10, SDP: 3 },
      'AB-': { WHOLE: 2, PRBC: 3, FFP: 5, PLATELETS: 1, SDP: 0 },
      'O+': { WHOLE: 30, PRBC: 62, FFP: 70, PLATELETS: 26, SDP: 8 },
      'O-': { WHOLE: 5, PRBC: 9, FFP: 12, PLATELETS: 4, SDP: 2 },
      'Bombay Group (Rare)': { WHOLE: 1, PRBC: 1, FFP: 2, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '08:00 AM - 08:00 PM (Daily)'
  },
  {
    id: 'BB-BBS-002',
    name: 'Capital Hospital Blood Bank, Bhubaneswar',
    nameOdia: 'କ୍ୟାପିଟାଲ୍ ହସ୍ପିଟାଲ୍ ରକ୍ତ ଭଣ୍ଡାର, ଭୁବନେଶ୍ୱର',
    hospitalName: 'Capital Hospital',
    district: 'Khurda (Bhubaneswar)',
    city: 'Bhubaneswar',
    address: 'Unit-6, Near Forest Park, Bhubaneswar - 751001',
    category: 'Govt District Hospital',
    bskyCovered: true,
    helpline: '+91 674 2391980 / 104',
    nodalOfficer: 'Dr. Debasis Swain',
    nodalPhone: '+91 98611 44520',
    email: 'bloodbank.capital@odisha.gov.in',
    operatingHours: '24x7 Emergency Services',
    lastUpdated: '2026-09-09T10:15:00.000Z',
    stock: {
      'A+': { WHOLE: 12, PRBC: 20, FFP: 28, PLATELETS: 8, SDP: 2 },
      'A-': { WHOLE: 1, PRBC: 2, FFP: 4, PLATELETS: 1, SDP: 0 },
      'B+': { WHOLE: 16, PRBC: 35, FFP: 40, PLATELETS: 15, SDP: 4 },
      'B-': { WHOLE: 2, PRBC: 3, FFP: 6, PLATELETS: 1, SDP: 0 },
      'AB+': { WHOLE: 8, PRBC: 14, FFP: 18, PLATELETS: 5, SDP: 1 },
      'AB-': { WHOLE: 0, PRBC: 1, FFP: 2, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 22, PRBC: 45, FFP: 50, PLATELETS: 18, SDP: 5 },
      'O-': { WHOLE: 3, PRBC: 5, FFP: 8, PLATELETS: 2, SDP: 1 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '09:00 AM - 05:00 PM'
  },
  {
    id: 'BB-MKCG-003',
    name: 'MKCG Medical College Blood Bank, Berhampur',
    nameOdia: 'ଏମ୍.କେ.ସି.ଜି. ମେଡିକାଲ୍ କଲେଜ୍ ରକ୍ତ ଭଣ୍ଡାର, ବ୍ରହ୍ମପୁର',
    hospitalName: 'MKCG Medical College & Hospital',
    district: 'Ganjam (Berhampur)',
    city: 'Berhampur',
    address: 'Medical College Campus, Berhampur - 760004',
    category: 'Govt Medical College',
    bskyCovered: true,
    helpline: '+91 680 2292700 / 104',
    nodalOfficer: 'Dr. Santosh Kumar Sahu',
    nodalPhone: '+91 94372 33410',
    email: 'bloodbank.mkcg@odisha.gov.in',
    operatingHours: '24x7 Emergency Services',
    lastUpdated: '2026-09-09T08:45:00.000Z',
    stock: {
      'A+': { WHOLE: 15, PRBC: 26, FFP: 30, PLATELETS: 10, SDP: 3 },
      'A-': { WHOLE: 2, PRBC: 3, FFP: 5, PLATELETS: 1, SDP: 0 },
      'B+': { WHOLE: 20, PRBC: 40, FFP: 45, PLATELETS: 16, SDP: 4 },
      'B-': { WHOLE: 3, PRBC: 4, FFP: 7, PLATELETS: 2, SDP: 0 },
      'AB+': { WHOLE: 10, PRBC: 18, FFP: 22, PLATELETS: 6, SDP: 2 },
      'AB-': { WHOLE: 1, PRBC: 2, FFP: 3, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 25, PRBC: 50, FFP: 58, PLATELETS: 20, SDP: 6 },
      'O-': { WHOLE: 4, PRBC: 6, FFP: 9, PLATELETS: 3, SDP: 1 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 1, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '08:30 AM - 06:00 PM'
  },
  {
    id: 'BB-VIM-004',
    name: 'VIMSAR Hospital Blood Bank, Burla',
    nameOdia: 'ଭିମ୍‌ସାର୍ ହସ୍ପିଟାଲ୍ ରକ୍ତ ଭଣ୍ଡାର, ବୁର୍ଲା',
    hospitalName: 'VSS Institute of Medical Sciences & Research (VIMSAR)',
    district: 'Sambalpur (Burla)',
    city: 'Burla',
    address: 'VIMSAR Hospital Campus, Burla, Sambalpur - 768017',
    category: 'Govt Medical College',
    bskyCovered: true,
    helpline: '+91 663 2430768 / 104',
    nodalOfficer: 'Dr. Subash Chandra Mishra',
    nodalPhone: '+91 94371 66201',
    email: 'bloodbank.vimsar@odisha.gov.in',
    operatingHours: '24x7 Emergency',
    lastUpdated: '2026-09-09T11:00:00.000Z',
    stock: {
      'A+': { WHOLE: 10, PRBC: 18, FFP: 24, PLATELETS: 7, SDP: 1 },
      'A-': { WHOLE: 1, PRBC: 2, FFP: 3, PLATELETS: 0, SDP: 0 },
      'B+': { WHOLE: 14, PRBC: 28, FFP: 36, PLATELETS: 11, SDP: 3 },
      'B-': { WHOLE: 2, PRBC: 3, FFP: 5, PLATELETS: 1, SDP: 0 },
      'AB+': { WHOLE: 6, PRBC: 12, FFP: 15, PLATELETS: 4, SDP: 1 },
      'AB-': { WHOLE: 0, PRBC: 1, FFP: 2, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 18, PRBC: 38, FFP: 42, PLATELETS: 14, SDP: 4 },
      'O-': { WHOLE: 2, PRBC: 4, FFP: 6, PLATELETS: 1, SDP: 0 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '09:00 AM - 05:00 PM'
  },
  {
    id: 'BB-BAL-005',
    name: 'FM Medical College & Hospital Blood Bank, Balasore',
    nameOdia: 'ଫକୀର ମୋହନ ମେଡିକାଲ୍ କଲେଜ୍ ରକ୍ତ ଭଣ୍ଡାର, ବାଲେଶ୍ୱର',
    hospitalName: 'Fakir Mohan Medical College & Hospital',
    district: 'Balasore',
    city: 'Balasore',
    address: 'Remuna, Balasore - 756019',
    category: 'Govt Medical College',
    bskyCovered: true,
    helpline: '+91 6782 220104 / 104',
    nodalOfficer: 'Dr. Sujata Priyadarshini',
    nodalPhone: '+91 94373 55190',
    email: 'bloodbank.fmmch@odisha.gov.in',
    operatingHours: '24x7 Emergency',
    lastUpdated: '2026-09-09T07:50:00.000Z',
    stock: {
      'A+': { WHOLE: 8, PRBC: 15, FFP: 20, PLATELETS: 5, SDP: 1 },
      'A-': { WHOLE: 1, PRBC: 1, FFP: 3, PLATELETS: 0, SDP: 0 },
      'B+': { WHOLE: 12, PRBC: 24, FFP: 30, PLATELETS: 8, SDP: 2 },
      'B-': { WHOLE: 1, PRBC: 2, FFP: 4, PLATELETS: 1, SDP: 0 },
      'AB+': { WHOLE: 5, PRBC: 9, FFP: 12, PLATELETS: 3, SDP: 0 },
      'AB-': { WHOLE: 0, PRBC: 1, FFP: 1, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 15, PRBC: 32, FFP: 38, PLATELETS: 12, SDP: 3 },
      'O-': { WHOLE: 2, PRBC: 3, FFP: 5, PLATELETS: 1, SDP: 0 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '09:00 AM - 04:30 PM'
  },
  {
    id: 'BB-KPT-006',
    name: 'SLN Medical College Blood Bank, Koraput',
    nameOdia: 'ଶାହୀଦ ଲକ୍ଷ୍ମଣ ନାୟକ ମେଡିକାଲ୍ କଲେଜ୍ ରକ୍ତ ଭଣ୍ଡାର, କୋରାପୁଟ',
    hospitalName: 'Saheed Laxman Nayak Medical College & Hospital',
    district: 'Koraput',
    city: 'Koraput',
    address: 'Janiguda, Koraput - 764020',
    category: 'Govt Tribal Regional Hospital',
    bskyCovered: true,
    helpline: '+91 6852 250104 / 104',
    nodalOfficer: 'Dr. Bijay Kumar Tudu',
    nodalPhone: '+91 94374 88120',
    email: 'bloodbank.slnmch@odisha.gov.in',
    operatingHours: '24x7 Emergency',
    lastUpdated: '2026-09-09T08:10:00.000Z',
    stock: {
      'A+': { WHOLE: 9, PRBC: 14, FFP: 18, PLATELETS: 4, SDP: 0 },
      'A-': { WHOLE: 1, PRBC: 2, FFP: 2, PLATELETS: 0, SDP: 0 },
      'B+': { WHOLE: 14, PRBC: 22, FFP: 26, PLATELETS: 7, SDP: 1 },
      'B-': { WHOLE: 1, PRBC: 2, FFP: 3, PLATELETS: 0, SDP: 0 },
      'AB+': { WHOLE: 4, PRBC: 8, FFP: 10, PLATELETS: 2, SDP: 0 },
      'AB-': { WHOLE: 0, PRBC: 0, FFP: 1, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 16, PRBC: 28, FFP: 32, PLATELETS: 9, SDP: 2 },
      'O-': { WHOLE: 2, PRBC: 3, FFP: 4, PLATELETS: 1, SDP: 0 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '09:00 AM - 04:00 PM'
  },
  {
    id: 'BB-RGH-007',
    name: 'Rourkela General Hospital (RGH) Blood Bank',
    nameOdia: 'ରାଉରକେଲା ଜେନେରାଲ୍ ହସ୍ପିଟାଲ୍ (RGH) ରକ୍ତ ଭଣ୍ଡାର',
    hospitalName: 'Rourkela General Hospital (RGH)',
    district: 'Sundargarh (Rourkela)',
    city: 'Rourkela',
    address: 'Panposh Road, Rourkela - 769004',
    category: 'Govt District Hospital',
    bskyCovered: true,
    helpline: '+91 661 2510104 / 104',
    nodalOfficer: 'Dr. Anupama Ekka',
    nodalPhone: '+91 94371 99312',
    email: 'bloodbank.rgh@odisha.gov.in',
    operatingHours: '24x7 Emergency',
    lastUpdated: '2026-09-09T10:00:00.000Z',
    stock: {
      'A+': { WHOLE: 11, PRBC: 19, FFP: 25, PLATELETS: 6, SDP: 1 },
      'A-': { WHOLE: 2, PRBC: 2, FFP: 4, PLATELETS: 1, SDP: 0 },
      'B+': { WHOLE: 15, PRBC: 30, FFP: 35, PLATELETS: 10, SDP: 2 },
      'B-': { WHOLE: 2, PRBC: 3, FFP: 5, PLATELETS: 1, SDP: 0 },
      'AB+': { WHOLE: 7, PRBC: 11, FFP: 14, PLATELETS: 3, SDP: 0 },
      'AB-': { WHOLE: 1, PRBC: 1, FFP: 2, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 20, PRBC: 40, FFP: 46, PLATELETS: 15, SDP: 4 },
      'O-': { WHOLE: 3, PRBC: 4, FFP: 6, PLATELETS: 1, SDP: 0 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '08:30 AM - 05:00 PM'
  },
  {
    id: 'BB-PURI-008',
    name: 'District Headquarter Hospital (DHH) Blood Bank, Puri',
    nameOdia: 'ଜିଲ୍ଲା ମୁଖ୍ୟ ଡାକ୍ତରଖାନା (DHH) ରକ୍ତ ଭଣ୍ଡାର, ପୁରୀ',
    hospitalName: 'District Headquarter Hospital, Puri',
    district: 'Puri',
    city: 'Puri',
    address: 'Grand Road, Near Jagannath Temple, Puri - 752001',
    category: 'Govt District Hospital',
    bskyCovered: true,
    helpline: '+91 6752 222104 / 104',
    nodalOfficer: 'Dr. Ramakanta Dash',
    nodalPhone: '+91 94370 51234',
    email: 'bloodbank.dhhpuri@odisha.gov.in',
    operatingHours: '24x7 Emergency',
    lastUpdated: '2026-09-09T09:00:00.000Z',
    stock: {
      'A+': { WHOLE: 7, PRBC: 13, FFP: 16, PLATELETS: 4, SDP: 0 },
      'A-': { WHOLE: 1, PRBC: 1, FFP: 2, PLATELETS: 0, SDP: 0 },
      'B+': { WHOLE: 11, PRBC: 21, FFP: 26, PLATELETS: 7, SDP: 1 },
      'B-': { WHOLE: 1, PRBC: 2, FFP: 3, PLATELETS: 0, SDP: 0 },
      'AB+': { WHOLE: 4, PRBC: 7, FFP: 10, PLATELETS: 2, SDP: 0 },
      'AB-': { WHOLE: 0, PRBC: 1, FFP: 1, PLATELETS: 0, SDP: 0 },
      'O+': { WHOLE: 14, PRBC: 28, FFP: 32, PLATELETS: 10, SDP: 2 },
      'O-': { WHOLE: 2, PRBC: 3, FFP: 4, PLATELETS: 1, SDP: 0 },
      'Bombay Group (Rare)': { WHOLE: 0, PRBC: 0, FFP: 0, PLATELETS: 0, SDP: 0 }
    },
    acceptingDonors: true,
    donorTimings: '09:00 AM - 05:00 PM'
  }
];

export const ODISHA_DONATION_CAMPS = [
  {
    id: 'CAMP-01',
    title: 'Utkal University Campus Blood Donation Drive',
    titleOdia: 'ଉତ୍କଳ ବିଶ୍ୱବିଦ୍ୟାଳୟ କ୍ୟାମ୍ପସ ରକ୍ତଦାନ ଶିବିର',
    organizer: 'Red Cross Odisha & Utkal University NSS Unit',
    location: 'Student Activity Centre, Utkal University, Vani Vihar, Bhubaneswar',
    district: 'Khurda (Bhubaneswar)',
    date: '2026-09-12',
    time: '09:00 AM - 04:00 PM',
    contact: '+91 94371 12345',
    targetUnits: 250
  },
  {
    id: 'CAMP-02',
    title: 'Cuttack Smart City Mega Blood Camp',
    titleOdia: 'କଟକ ସ୍ମାର୍ଟ ସିଟି ମେଗା ରକ୍ତଦାନ ଶିବିର',
    organizer: 'Odisha State Blood Transfusion Council (OSBTC) & SCBMCH',
    location: 'Barabati Stadium Pavilion, Cuttack',
    district: 'Cuttack',
    date: '2026-09-15',
    time: '08:30 AM - 05:00 PM',
    contact: '+91 94370 88210',
    targetUnits: 500
  },
  {
    id: 'CAMP-03',
    title: 'Berhampur Youth Rotary Blood Drive',
    titleOdia: 'ବ୍ରହ୍ମପୁର ଯୁବ ରୋଟାରୀ ରକ୍ତଦାନ ଶିବିର',
    organizer: 'Rotary Club Berhampur & MKCG Blood Bank',
    location: 'Town Hall, Near Bus Stand, Berhampur',
    district: 'Ganjam (Berhampur)',
    date: '2026-09-18',
    time: '09:00 AM - 03:30 PM',
    contact: '+91 94372 33410',
    targetUnits: 200
  },
  {
    id: 'CAMP-04',
    title: 'Rourkela Steel City Community Donation Camp',
    titleOdia: 'ରାଉରକେଲା ଇସ୍ପାତ ନଗରୀ ସାମୁହିକ ରକ୍ତଦାନ ଶିବିର',
    organizer: 'RGH Blood Bank & RSP Voluntary Donors',
    location: 'Sector 5 Community Centre, Rourkela',
    district: 'Sundargarh (Rourkela)',
    date: '2026-09-20',
    time: '09:30 AM - 04:30 PM',
    contact: '+91 94371 99312',
    targetUnits: 300
  }
];
